# .github/workflows/ci.yml
# name: CI
# on:
#   push:
#     branches: [main]
#
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository
#       uses: actions/checkout@v2
#
#       - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'
#
#       - name: Run Python script
#       env:
#         YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
#         WEBSHARE_PROXY_USER: ${{ secrets.WEBSHARE_PROXY_USER }}
#         WEBSHARE_PROXY_PASSWORD: ${{ secrets.WEBSHARE_PROXY_PASSWORD }}
#         GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
#       run: python src\main.py
